# -*- ruby -*-

# Try to load development version of evoker
EVOKER_DIR = File.expand_path('~/Projekty/evoker/lib')
$:.unshift(EVOKER_DIR) if File.exists?(EVOKER_DIR)

require 'evoker'
include Evoker

def tarball(basename, options={})
  tarball = wget options[:url]
  entity basename => tarball do
    sh "#{options[:decompress] || 'tar -xzf'} #{tarball}"
    ln_s File.basename(options[:url], options[:ext] || '.tar.gz'), basename unless options[:no_symlink]
  end
end

def emacswiki(filename)
  wget "http://www.emacswiki.org/cgi-bin/wiki/download/#{filename}"
end

def darcs(url)
  entity File.basename(url) do
    sh "darcs clone #{url}"
  end
end

subversion 'python-mode', :url => 'https://python-mode.svn.sourceforge.net/svnroot/python-mode/trunk/python-mode'
darcs 'http://chneukirchen.org/repos/darcsum/'
subversion 'ess', :url => 'https://svn.r-project.org/ESS/trunk/'

# Compile big projects to .elc

task 'gnuplot-mode' do
  sh 'cd gnuplot-mode && ./configure && make'
end

task 'auctex' do
  sh <<-EOF
    cd auctex && ./configure \
      --prefix=\`pwd\`/+INSTALL \
      --with-texmf-dir=$HOME/Library/texmf \
      --with-lispdir=$HOME/.emacs.d/lisp/site-lisp \
      && make && make install
  EOF
end

# Compile all single .el files to .elc

entity :elc => ENTITIES do
  sh '/usr/local/bin/emacs -batch -f batch-byte-compile *.el ||:'
end

task :default => ENTITIES
