;; Packages that need only loading, no customisation.

(require 'cc-vars)
(require 'sierotki)
(require 'filladapt)
(require 'css-mode)
(require 'boxquote)
(require 'psvn)
(require 'uniquify)
(require 'ess-site)
(require 'gnuplot)
(require 'moccur-edit)
(require 'scratch)
(require 'markdown-mode)
(require 'magit)
(require 'paredit)
(require 'coffee-mode)
(require 'ledger-mode)
(load "auctex")
(load "preview-latex")
(load "darcsum/darcsum")
(load "php-mode/php-mode")
(load "python-mode/python-mode")
(load "cucumber.el/feature-mode.el")
(load "yaml-mode/yaml-mode")
(load "haml-mode/haml-mode")
(load "scss-mode/scss-mode")
(load "nxhtml/nxhtml/nxml-where")
