(mouse-avoidance-mode 'exile)
(global-font-lock-mode 1)
(column-number-mode 1)
(auto-compression-mode 1)
(blink-cursor-mode 0)
(menu-bar-mode 1)
(tool-bar-mode 0)
(recentf-mode 1)
(auto-image-file-mode 1)
(size-indication-mode 1)
(pretty-symbols-mode 1)
(display-time)
(electric-pair-mode 1)
(ido-mode 1)
